### PR TITLE
Add support for Thesan's Cartesian outputs

### PR DESCRIPTION
**Pull request by EGaraldi**
Include a new submodule named cartesian to load fields from the Thesan-specific Cartesian outputs.

### CODE REVIEW

**Comment by dnelson** [comment]
Hi Enrico, thanks for this - can I ask what a Cartesian file is? How general is it?

I ask because the "illustris_python" is, so far, very general. It doesn't even have 'support' for loading many data products of Illustris/TNG, such as subbox, or postprocessing data catalogs. Thus I'm wondering how specific it should be made - what do you think?

**Comment by EGaraldi** [comment]
Hi Dylan,
I personally find it useful to have support for more data product (I have my own version of it), as long as the system is modular so that any product can be missing. However, I understand that the more feature are added, the heavier the maintenance of the module becomes. In fact, I only added support for the Cartesian output because they are - in Thesan - one of the main outputs, on par with the snapshots, and they are quite easy to handle and to generalize (they are basically a flattened grid split into chunks plus a header). That said, if you prefer not to introduce any functionality, I can easily maintain a Thesan-specific fork.

**Comment by dnelson** [comment]
I think no harm done. Can you just change the second line of `cartesian.py` to say clearly this is "THESAN-only" (for the time being), in case someone wanders into this file and is confused what it is for.

**Comment by EGaraldi** [comment]
Ok, great! I have added a comment as you suggested (also in the twin packages for IDL, julia and MATLAB)

**Pull request merged**
